services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mi_red

  php:
    image: php:8.1.30-fpm
    container_name: php8.1.30
    volumes:
      - ./:/var/www/html
    networks:
      - mi_red

networks:
  mi_red:
